version: '3.2'

networks:
  net:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - net
    php72:
        build:
            context: .
            dockerfile: ./dockerfiles/php72
        container_name: php72
        volumes:
            - ./src:/var/www/html
            - ./settings/php-ini/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./settings/php-ini/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
        extra_hosts:
            - "host.docker.internal:host-gateway"
        profiles:
            - php72
        networks:
            - net
    php80:
        build:
            context: .
            dockerfile: ./dockerfiles/php80
        container_name: php80
        volumes:
            - ./src:/var/www/html
            - ./settings/php-ini/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./settings/php-ini/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
        extra_hosts:
            - "host.docker.internal:host-gateway"
        profiles:
            - php80
        networks:
            - net