version: '3.2'

networks:
  lan:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - lan
    php:
        build:
            context: .
            dockerfile: ./dockerfiles/php
        container_name: php
        volumes:
            - ./src:/var/www/html:cache
            - ./settings/php-ini/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./settings/php-ini/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
        networks:
            - lan